- hosts: all

    # Install packages
   #- name: install yum-utils
   #  yum: name=yum-utils state=latest
   #- name: update all packages
   #  yum: name=* state=latest
   #- name: install epel-release
   #  yum: name=epel-release state=latest
    - name: install other packages
      yum: name=git,vim,atomic,docker,bash-completion state=latest

    # Configure and start docker
    - name: Add more docker storage configuration
      lineinfile: dest=/etc/sysconfig/docker-storage-setup regexp=^STORAGE_DRIVER= line=STORAGE_DRIVER=overlay2
    - name: ensure docker is running (and enable it at boot)
      service: name=docker state=started enabled=yes
